[[rules]]
id = "aws-access-key"
description = "AWS Access Key"
regex = '''AWS_ACCESS_KEY_ID=AKIA[0-9A-Z]{16}'''
tags = ["aws", "key"]

[[rules]]
id = "aws-secret-key"
description = "AWS Secret Access Key"
regex = '''AWS_SECRET_ACCESS_KEY=[0-9a-zA-Z/+]{40}'''
tags = ["aws", "secret"]

